server:
  port: ${PORT}

spring:
  application:
    name: CognitiveServices
  r2dbc:
    url: ${URL_DB}/${NAME_DB}
    username: ${USER_DB}
    password: ${PASSWORD_DB}

management:
  endpoint:
    health:
      show-details: always
      details:
        enabled: true