server:
  port: 9090

spring:
  application:
    name: CognitiveServices
  r2dbc:
    url: r2dbc:postgresql://viaduct.proxy.rlwy.net:38257/railway
    username: postgres
    password: LHzkFQedkDZnIXGPVTatvmIWMuyPQoau

