server:
  port: 9090
  servlet:
    context-path: /api/v1

spring:
  codec:
    max-in-memory-size: 10MB
  application:
    name: CognitiveServices

  r2dbc:
    url: r2dbc:postgresql://roundhouse.proxy.rlwy.net:16725/railway
    username: postgres
    password: pbjHWeAQiqEiqUvxBSNKChiSQFWmwURU
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

management:
  endpoint:
    health:
      show-details: always