server:
  port: 9090

spring:
  application:
    name: CognitiveServices
  r2dbc:
    url: r2dbc:postgresql://roundhouse.proxy.rlwy.net:16725/railway
    username: postgres
    password: pbjHWeAQiqEiqUvxBSNKChiSQFWmwURU

